### ISSUE TITLE
Not working anymore on Catalina

### ISSUE THREAD

**Issue by Quorum75** [ddddxxx/LyricsX#316] opened 2019-12-10 15:45 UTC
Hi.

The AS version 1.5.1 does not work anymore on macOS Catalina 10.15.1.

Even the menu access "Lyrics" above "Preferences" is greyed out.

Best
Bruno

**Comment by ShantanuNair** [comment] 2019-12-11 05:09
Same issue here. Seems like it is currently incompatible with the Music app.

**Comment by ddddxxx** [comment] 2019-12-19 09:49
Grey "Lyrics" menu means no lyrics available. It's probably caused by #317: You don't have LRC file,  and LyricsX doesn't search for you.

**Comment by Quorum75** [comment] 2019-12-19 10:13
@ddddxxx What do you mean by LRC file?

**Comment by ddddxxx** [comment] 2019-12-19 10:27
You don't need to care about this if you don't manage lyrics file yourself. Anyway, grey "Lyrics" menu is not the problem. The real problem is #137. Closing this.

**Closed by ddddxxx** 2019-12-19 10:27 UTC
